fix: remove duplicate --help and --version flags from bashly.yml
- Remove manual flag definitions for --help and --version
- Bashly automatically provides these flags, so manual definitions caused duplicates
- Help output now shows clean, single entries for --help and --version
- Both --help and --version commands still work correctly
- Fixes duplicate entries in help output that showed:
  - --version, -V and --version, -v
  - --help, -h and --help, -h

diff --git a/bamon b/bamon
--- a/bamon
+++ b/bamon
@@ -20,12 +20,13 @@ bamon_usage() {
   printf "bamon - Bash Daemon Monitor - A tool for monitoring and executing bash scripts\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  bamon [OPTIONS] COMMAND\n"
-  printf "  bamon [COMMAND] --help\n"
+  printf "  bamon COMMAND\n"
+  printf "  bamon [COMMAND] --help | -h\n"
   printf "  bamon --version | -v\n"
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   Generate bash completions\n" "completions"
   printf "  %s   Display current status of all configured scripts\n" "status     "
   printf "  %s   Add a new script to monitor\n" "add        "
   printf "  %s   Remove a script from monitoring\n" "remove     "
@@ -40,25 +41,40 @@ bamon_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
-    printf "%s\n" "Global Options:"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "--version, -V"
-    printf "    Show version information\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "--help, -h"
-    printf "    Show help information\n"
-    echo
+    printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help"
+    printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+bamon_completions_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "bamon completions\n\n"
+    printf "  Generate bash completions\n  Usage: eval \"\$(cli completions)\"\n\n"
+  else
+    printf "bamon completions - Generate bash completions\n\n"
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  bamon completions\n"
+  printf "  bamon completions --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -2519,7 +2535,125 @@ function validate_sandbox_config() {
   return 0
 }
 
+# src/lib/send_completions.sh
+send_completions() {
+  echo $'# bamon completion                                         -*- shell-script -*-'
+  echo $''
+  echo $'# This bash completions script was generated by'
+  echo $'# completely (https://github.com/bashly-framework/completely)'
+  echo $'# Modifying it manually is not recommended'
+  echo $''
+  echo $'_bamon_completions_filter() {'
+  echo $'  local words="$1"'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local result=()'
+  echo $''
+  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
+  echo $'    echo "$words"'
+  echo $''
+  echo $'  else'
+  echo $'    for word in $words; do'
+  echo $'      [[ "${word:0:1}" != "-" ]] && result+=("$word")'
+  echo $'    done'
+  echo $''
+  echo $'    echo "${result[*]}"'
+  echo $''
+  echo $'  fi'
+  echo $'}'
+  echo $''
+  echo $'_bamon_completions() {'
+  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
+  echo $'  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")'
+  echo $'  local compline="${compwords[*]}"'
+  echo $''
+  echo $'  case "$compline" in'
+  echo $'    *\'config validate\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--help --verbose -h -v")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'config reset\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--force --help -f -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'completions\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--help -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'performance\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--format --help --json --verbose -f -h -v")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'config edit\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--editor --help -e -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'config show\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--help --pretty -h -p")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'restart\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--config --daemon --help -c -d -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'status\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--failed-only --help --json --name --verbose -f -h -j -n -v")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'remove\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--force --help -f -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'config\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--help -h edit reset show validate")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'start\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--config --daemon --help -c -d -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'stop\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--force --help -f -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'list\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--disabled-only --enabled-only --help -d -e -h")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'add\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--command --description --disabled --enabled --help --interval -c -d -h -i")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *\'now\'*)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--async --help --name -a -h -n")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'    *)'
+  echo $'      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_bamon_completions_filter "--help --version -V -h -v add completions config list now performance remove restart start status stop")" -- "$cur")'
+  echo $'      ;;'
+  echo $''
+  echo $'  esac'
+  echo $'} &&'
+  echo $'  complete -F _bamon_completions bamon'
+  echo $''
+  echo $'# ex: filetype=sh'
+}
+
 # :command.command_functions
+# :command.function
+bamon_completions_command() {
+
+  # src/completions_command.sh
+  # Call the `send_completions` function which was added by running:
+  #
+  #   $ bashly add completions
+  #
+  # Users can now enable bash completion for this script by running:
+  #
+  #   $ eval "$(bamon completions)"
+  #
+  send_completions
+}
+
 # :command.function
 bamon_status_command() {
 
@@ -3681,26 +3815,10 @@ parse_requirements() {
         exit
         ;;
 
-      --help)
+      --help | -h)
         long_usage=yes
         bamon_usage
         exit
-        ;;
-
-      # :flag.case
-      --version | -V)
-
-        # :flag.case_no_arg
-        args['--version']=1
-        shift
-        ;;
-
-      # :flag.case
-      --help | -h)
-
-        # :flag.case_no_arg
-        args['--help']=1
-        shift
         ;;
 
       *)
@@ -3715,6 +3833,13 @@ parse_requirements() {
 
   case $action in
     -*) ;;
+
+    completions)
+      action="completions"
+      shift
+      bamon_completions_parse_requirements "$@"
+      shift $#
+      ;;
 
     status)
       action="status"
@@ -3798,6 +3923,51 @@ parse_requirements() {
       ;;
 
   esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+bamon_completions_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        bamon_completions_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="completions"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -4797,6 +4967,7 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "completions") bamon_completions_command ;;
     "status") bamon_status_command ;;
     "add") bamon_add_command ;;
     "remove") bamon_remove_command ;;
